name: microservice-spa-starter
services:
  certs-setup:
    build:
      context: ./setup/certs
      tags:
        - certs-setup:latest
    volumes:
      - ./data/certs:/certs
    environment:
      - CA=microservice-spa-starter.local
      - CLIENTS=elasticsearch,kibana,apm-server
  elasticsearch:
    image: elasticsearch:8.15.0
    depends_on:
      certs-setup:
        condition: service_completed_successfully
    environment:
      - node.name=elasticsearch
      - ELASTIC_PASSWORD=elastic
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/elasticsearch/client.key
      - xpack.security.http.ssl.certificate=certs/elasticsearch/client.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/elasticsearch/client.key
      - xpack.security.transport.ssl.certificate=certs/elasticsearch/client.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
    ports:
      - "9200:9200"
    volumes:
      - ./data/certs/ca:/usr/share/elasticsearch/config/certs/ca:ro
      - ./data/certs/elasticsearch:/usr/share/elasticsearch/config/certs/elasticsearch:ro
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD-SHELL", "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'" ]
      interval: 10s
      timeout: 10s
      retries: 120
  elasticsearch-init:
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTIC_PASSWORD=elastic
      - KIBANA_PASSWORD=kibana
    image: elasticsearch:8.15.0
    volumes:
      - ./data/certs/ca:/usr/share/elasticsearch/config/certs/ca:ro
      - ./setup/elasticsearch/elasticsearch.setup.sh:/usr/share/elasticsearch/elasticsearch.setup.sh
    command: [ "sh", "./elasticsearch.setup.sh" ]
  kibana:
    image: kibana:8.15.0
    depends_on:
      elasticsearch:
        condition: service_healthy
      elasticsearch-init:
        condition: service_completed_successfully
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY=config/certs/kibana/client.key
      - SERVER_SSL_CERTIFICATE=config/certs/kibana/client.crt
    ports:
      - "5601:5601"
    volumes:
      - ./data/certs/ca:/usr/share/kibana/config/certs/ca:ro
      - ./data/certs/kibana:/usr/share/kibana/config/certs/kibana:ro
      - ./data/kibana:/usr/share/kibana/data
    mem_limit: 1073741824
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -I --cacert config/certs/ca/ca.crt https://localhost:5601 | grep -q 'HTTP/1.1 302 Found'" ]
      interval: 10s
      timeout: 10s
      retries: 1
  apm-server:
    image: elastic/apm-server:8.15.0
    depends_on:
      elasticsearch:
        condition: service_healthy
      elasticsearch-init:
        condition: service_completed_successfully
    ports:
      - "8200:8200"
    volumes:
      - ./data/certs/ca:/usr/share/apm-server/config/certs/ca:ro
      - ./data/certs/apm-server:/usr/share/apm-server/config/certs/apm-server:ro
      - ./setup/apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    healthcheck:
      test: ["CMD", "curl --write-out 'HTTP %{http_code}' --silent --output /dev/null --cacert config/certs/ca/ca.crt https://localhost:8200/healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 120
