server:
  port: 8089
  forward-headers-strategy: framework
  servlet:
    context-path: /auth
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.security: trace
spring:
  security:
    user:
      name: username
      password: password
    oauth2:
      client:
        registration:
          github:
            provider: github
            client-id: '{cipher}f45df2b9a37672133e1df7f8d5362133c7a78a92db652050bc69555e9145c7743b00d874b676f4c571b73c403625a4a1'
            client-secret: '{cipher}e67735f0df60b8fe1872e51b4f72c11440063eae2355d79b7bcd8d4903e0f5f449500958c00833c6e307586d85cbe3720f0586075f7404f23b5bf18871e41a3b'
            scope: user:email, read:user
            client-name: GitHub
        provider:
          github:
            user-name-attribute: id
      authorizationserver:
        client:
          gateway:
            registration:
              client-id: gateway-client
              client-secret: '{noop}gateway-secret'
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://localhost:8080/login/oauth2/code/gateway
                - http://localhost:8080/api/login/oauth2/code/gateway
                - http://localhost:5173/api/login/oauth2/code/gateway
              post-logout-redirect-uris:
                - http://localhost:8080/api/..
                - http://localhost:5173/api/..
              scopes:
                - openid
                - profile
  devtools:
    livereload:
      enabled: false
