server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  devtools:
    livereload:
      enabled: false
    restart:
      additional-paths: be-srv-config/build/resources/main/config/
