server:
  port: 8761
  other: true
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  devtools:
    restart:
      additional-paths: .,../../../../be-srv-config/src/main/resources/config/discovery-service.yml
